# Generated by Django 5.0.1 on 2024-02-15 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_perfil_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
    ]
