# Generated by Django 5.0.1 on 2024-02-20 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_perfil_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseña',
            old_name='reseña',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='reseña',
            old_name='nombre',
            new_name='name',
        ),
    ]
