# Generated by Django 5.0.1 on 2024-02-22 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_reseña_reseña_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseña',
            old_name='name',
            new_name='first_name',
        ),
    ]
